language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux
notifications:
  slack: marsysteam:kR5O6wXobf3Ze1by5cMPsFcG
before_install:
- echo $LANG
- echo $LC_ALL
- sudo rm -rf /var/lib/apt/lists/*
- sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 1397BC53640DB551
- sudo apt-get update -qq
- sudo apt-get install libsdl2-dev -y
- sudo apt-get install libcppunit-dev -y
- sudo apt-get install libncurses5-dev -y
- pip install --user cpp-coveralls
before_script:
script:
- make
- cd lesson
- make
- make -f Makefile.scrap
- cd ..
- cd rogue
- make
- cd ..
after_success:
- coveralls --exclude lib --exclude tests --gcov-options '\-lp'