language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux
notifications:
  slack: marsysteam:kR5O6wXobf3Ze1by5cMPsFcG
before_install:
- echo $LANG
- echo $LC_ALL
- sudo apt-get update -qq
- sudo apt-get install libsdl2-dev -y
before_script:
script: make
after_success:
- ./game