#OBJS specifies which files to compile as part of the project
OBJS = db.cpp

#CC specifies which compiler we're using
CC = g++

#COMPILER_FLAGS specifies the additional compilation options we're using
# -w suppresses all warnings
COMPILER_FLAGS = -w $(shell mysql_config --cflags )
MAC_COMPILER_FLAGS = -w

#LINKER_FLAGS specifies the libraries we're linking against
LINKER_FLAGS = $(shell mysql_config --libs)

#OBJ_NAME specifies the name of our exectuable
OBJ_NAME = db

#This is the target that compiles our executable
all : $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)

Mac : $(OBJS)
	$(CC) $(OBJS) $(MAC_COMPILER_FLAGS) $(MAC_LINKER_FLAGS) -o $(OBJ_NAME)
